export const Data = [
  {
    img: "/images/menproducts/m2.jpg",
    name: "Solid Elasticated Joggers",
    price: 698,
    rating: " 4.7",
    idtype: "eye",
    prodID: 1,
  },
  {
    img: "/images/menproducts/m3.jpg",
    name: " Solid Slim Fit Polo T-shirt",
    price: 299,
    rating: " 4.7",
    idtype: "T-shirt",
    prodID: 2,
  },
  {
    img: "/images/menproducts/m4.jpg",
    name: " Solid Crew Neck Lounge T-shirt",
    price: 399,
    idtype: "T-shirt",
    rating: " 4.6",
    prodID: 3,
  },
  {
    img: "/images/menproducts/m5.jpg",
    name: "Striped Elasticated Waist Shorts",

    price: 99,
    idtype: "shorts",
    rating: "4.9",
    prodID: 4,
  },
  {
    img: "/images/menproducts/m6.jpg",
    name: "Solid Mandarin Collar Slim Fit Casual Shirt",
    price: 399,
    idtype: "shirt",
    rating: " 4.9",
    prodID: 5,
  },
  {
    img: "/images/menproducts/m7.jpg",
    name: "Solid Elasticated Waist Lounge Shorts - Pack Of 2",
    price: 199,
    idtype: "shorts",
    rating: "4.8",
    prodID: 6,
  },
  {
    img: "/images/menproducts/m8.jpg",
    name: "Solid Mandarin Collar Slim Fit Casual Shirt",
    price: 599,
    idtype: "shirt",
    rating: "4.8",
    prodID: 7,
  },
  {
    img: "/images/menproducts/m9.jpg",
    name: "MAX men Textured Sports wear",
    price: 99,
    idtype: "joggers",
    rating: " 4.8",
    prodID: 8,
  },
  {
    img: "/images/menproducts/m10.jpg",
    name: " Floral Printed High Neck A-line",
    price: 399,
    rating: "4.7",
    idtype: "T-shirt",
    prodID: 9,
  },
  {
    img: "/images/menproducts/m11.jpg",
    name: "Printed A-Line Dress",
    price: 599,
    rating: "4.7",
    idtype: "t-shirt",
    prodID: 10,
  },
  {
    img: "/images/menproducts/m12.jpg",
    name: "MAX men Textured Sports Shoes",
    price: 879,
    rating: "4.7",
    idtype: "footwear",
    prodID: 11,
  },
  {
    img: "/images/menproducts/m1.jpg",
    name: "MAX Men Solid Crew Neck T-shirt - Set of 2",
    price: 129,
    rating: "4.7",
    idtype: "T-shirt",
    prodID: 12,
  },
  {
    img: "/images/menproducts/m13 (1).jpg",
    name: "Striped Laced-Up Shoes",
    price: 99,
    rating: "4.7",
    idtype: "footwear",
    prodID: 13,
  },
  {
    img: "/images/menproducts/m13 (2).jpg",
    name: "Flat",
    price: 599,
    rating: "4.7",
    idtype: "footwear",
    prodID: 14,
  },
  {
    img: "/images/menproducts/m13 (3).jpg",
    name: "Flipflops",
    price: 899,
    rating: "4.7",
    idtype: "footwear",
    prodID: 15,
  },
  {
    img: "/images/menproducts/m13 (4).jpg",
    name: "shoes",
    price: 199,
    rating: "4.7",
    idtype: "footwear",
    prodID: 16,
  },
];
